name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: 0.14.0-alpha+1
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+22
  googleapis: any
  googleapis_auth: any
  firebase: ^5.0.0


dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.4
